language: node_js
sudo: required

branches:
  only:
    - master

services:
  - mongodb
  - docker

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - echo "skipping tests"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
