branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Unit Tests: Node 8"
      language: node_js
      sudo: required

      node_js:
        - "8"

      branches:
        only:
          - master

      services:
        - mongodb
        - docker

      install:
        - npm install

      before_install:
        - docker pull fiware/orion:latest
        - docker run -d --net host -l orion fiware/orion:latest
        - docker pull ansi/mosquitto
        - docker run -d --net host -l mosquitto ansi/mosquitto
        - npm update -q

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Unit Tests: Node 10"
      language: node_js
      sudo: required

      node_js:
        - "10"

      branches:
        only:
          - master

      services:
        - mongodb
        - docker

      install:
        - npm install

      before_install:
        - docker pull fiware/orion:latest
        - docker run -d --net host -l orion fiware/orion:latest
        - docker pull ansi/mosquitto
        - docker run -d --net host -l mosquitto ansi/mosquitto
        - npm update -q

      before_script:
        - npm run lint

      after_script:
        - npm run test:coveralls

    - stage: test
      name: "Documentation Tests"
      language: node_js

      node_js:
        - "10"

      install:
        - npm install

      script:
        - npm run lint:md
        - npm run lint:text
