language: node_js
sudo: required

node_js:
 - "8"
 - "10"

branches:
  only:
    - master

services:
  - mongodb
  - docker

install:
  - npm install

before_install:
  - docker pull fiware/orion:latest
  - docker run -d --net host -l orion fiware/orion:latest
  - docker pull ansi/mosquitto
  - docker run -d --net host -l mosquitto ansi/mosquitto
  - npm update -q

before_script:
  - npm run lint
  - npm run lint:text
  - npm run lint:md

after_script: 
  - npm run test:coveralls