site_name: LoRaWAN IoT Agent 
site_url: https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN
repo_url: https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN
site_description: FIWARE IoT Agent for LoRaWAN protocol document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_iot.css"]
pages:
    - Home: index.md
    - Installation guide: installationguide.md
    - Users manual: users_manual.md
    - Development manual: development_manual.md
    - Contributing: CONTRIBUTING.md
    
