version: "3.7"

services:
  mongodb:
    extends:
      file: docker-compose-dev.yml
      service: mongodb
    volumes:
      - mongo_data:/data/db

  orion:
    extends:
      file: docker-compose-dev.yml
      service: orion
    command: -dbhost mongodb -port 1026 -logLevel INFO

  iotagent-lora:
    depends_on:
      - mongodb
      - orion
    entrypoint: bin/iotagent-lora docker/config-docker.js
    hostname: iotagent-lora
    image: ioeari/iotagent-lora
    ports:
      - "4041:4041"
    networks:
      - LoRaWAN

volumes:
  mongo_data:

networks:
  LoRaWAN: {}
