version: "3.7"
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - LoRaWAN

  orion:
    image: fiware/orion:${ORION_VERSION:-3.3.1}
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -noCache -dbhost mongodb
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - LoRaWAN

  mqtt:
    image: ansi/mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
    networks:
      - LoRaWAN

networks:
  LoRaWAN: {}
