# This action works with pull requests and pushes
name: Code Linter

on:
  ? pull_request
  push:
    branches:
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: yarn install
      - name: ESLint
        run: npx --no-install eslint lib/ test/ --cache
      - name: Prettier
        run: npx --no-install prettier --config .prettierrc.json --check '**/**/**/*.js' '**/**/*.js' '**/*.js' '*.js'
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: yarn install
      - name: lint:md
        run: npm run lint:md
      - name: lint:text
        run: npm run lint:text
