# This action works with pull requests and pushes
name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    env:
      COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd docker/mosquitto/config-ssl/certs
          bash generate-ca.sh
          cd ../../..
          docker compose -f docker-compose-dev.yml up -d
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: "Unit Tests with Node.js ${{ matrix.node }}"
        run: |
          npm install
          npm test
      - run: |
          cd docker
          docker compose -f docker-compose-dev.yml down -v
  code-coverage:
    name: Coveralls Code Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: "Test Coverage with Node.js 12.x"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: |
          cd docker/mosquitto/config-ssl/certs
          bash generate-ca.sh
          cd ../../..
          docker compose -f docker-compose-dev.yml up -d
      - run: |
          npm install
          npm run test:coverage
      - name: Push to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cd docker
          docker compose -f docker-compose-dev.yml down -v
